"""Add effective_start_date and effective_end_date to whitelist_entries

Revision ID: 2b719a67ab1a
Revises: 4a1d4c4f48ab
Create Date: 2024-12-23 14:59:23.914307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b719a67ab1a'
down_revision = '4a1d4c4f48ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist_entries', schema=None) as batch_op:
        batch_op.drop_column('effective_start_date')
        batch_op.drop_column('effective_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_end_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('effective_start_date', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
